### ISSUE TITLE
Can't seem to `npm install`

### ISSUE THREAD

**Issue by shaansheikh** [Colorsublime/Colorsublime-Themes#194] opened 2015-08-30 04:23 UTC
I get the following error when attempting to `npm install`. Does anybody know why this is or what's going on? I don't have much experience with node.
 
    npm WARN package.json color-parser@0.1.0 No repository field.
     /
     > libxmljs@0.14.3 install /home/shaan/Desktop/Colorsublime-Themes/node_modules/libxmljs
     > node-gyp rebuild
    
    /bin/sh: 1: node: not found
    gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
    gyp ERR! configure error 
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
    gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
    gyp ERR! System Linux 3.19.0-26-generic
    gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
    gyp ERR! cwd /home/shaan/Desktop/Colorsublime-Themes/node_modules/libxmljs
    gyp ERR! node -v v0.10.25
    gyp ERR! node-gyp -v v0.12.2
    gyp ERR! not ok 
    npm WARN This failure might be due to the use of legacy binary "node"
    npm WARN For further explanations, please read
    /usr/share/doc/nodejs/README.Debian
     
    npm ERR! libxmljs@0.14.3 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the libxmljs@0.14.3 install script.
    npm ERR! This is most likely a problem with the libxmljs package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls libxmljs
    npm ERR! There is likely additional logging output above.
    
    npm ERR! System Linux 3.19.0-26-generic
    npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
    npm ERR! cwd /home/shaan/Desktop/Colorsublime-Themes
    npm ERR! node -v v0.10.25
    npm ERR! npm -v 1.4.21
    npm ERR! code ELIFECYCLE
    npm ERR! 
    npm ERR! Additional logging details can be found in:
    npm ERR!     /home/shaan/Desktop/Colorsublime-Themes/npm-debug.log
    npm ERR! not ok code 0

**Comment by GianlucaGuarini** [comment] 2015-08-30 07:56
try `sudo npm install`

**Comment by shaansheikh** [comment] 2015-09-05 22:14
no dice. Same error

**Comment by aflat** [comment] 2016-06-29 15:26
I had to run a patched version to get it to work on OSX(and probably would do the same on linux)
`npm install adriancooney/libxmljs`
from
https://github.com/libxmljs/libxmljs/issues/400

In addition, from the bit I read to add this comment, it looks like it might be fixed in libxmljs 0.18, but that is unconfirmed by me

**Comment by blopker** [comment] 2016-06-29 18:08
I have a PR to update libxmljs, can you try it out? If that doesn't work: what does `node -v` and `g++ -v` put out for you?

**Comment by aflat** [comment] 2016-06-30 17:08
cloned a clean repo and tried it, seems to work just fine. Merge it!

**Closed** 2016-07-20 18:10 UTC
